package jace.hardware.mockingboard;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;

import jace.core.Utility;
import jace.hardware.CardMockingboard;

/**
 * Verifies the amplitude (DAC) table against empirical measurements of a real
 * AY-3-8910.
 *
 * <h3>Which chip, and why it matters</h3>
 * A Mockingboard uses the <b>AY-3-8913</b>: the same PSG core as the AY-3-8910
 * in a 24-pin package with the parallel I/O ports omitted. Two independent
 * confirmations:
 * <ul>
 *   <li>AppleWin's {@code Mockingboard.cpp} names the part throughout --
 *       {@code class AY8913}, {@code AY8913_Write}, {@code AY8913_Reset},
 *       {@code NUM_AY8913_PER_SUBUNIT} -- and its comment at GH#1192 reads
 *       "AY1 is the primary AY-3-8913 connected to 6522".</li>
 *   <li>MAME models {@code ay8913_device} as
 *       {@code ay8910_device(..., PSG_TYPE_AY, 3, 0)} (ay8910.cpp:1630-1631):
 *       identical core, 3 sound streams, <b>0</b> I/O ports. Because it is
 *       {@code PSG_TYPE_AY}, ay8910.cpp:1578-1579 selects
 *       {@code ay8910_param} for <i>both</i> the tone and the envelope table,
 *       and ay8910.cpp:1575 sets {@code m_env_step_mask = 0x0f}.</li>
 * </ul>
 * So the correct table is the <b>AY-3-8910</b> one, with <b>16</b> levels shared
 * by tone and envelope. The YM2149's 32-entry {@code ym2149_param_env} does
 * <em>not</em> apply. That matches Jace's structure: {@code EnvelopeGenerator}
 * counts 0..15 and indexes the same 16-entry {@code VolTable} through
 * {@code SoundGenerator.step}, so no structural change is needed.
 *
 * <h3>The measurements</h3>
 * MAME's active {@code ay8910_param} (ay8910.cpp:717-722) is a table of
 * <em>output resistances</em>, not levels, annotated "RL = 2000, Based on
 * Matthew Westcott's measurements from Dec 2001". Those readings were taken by
 * forcing a constant voltage on channel C (register 6 bits 2 and 5) and sweeping
 * the low 4 bits of register 10, measuring pin 1 against ground:
 *
 * <pre>
 *   level: 0      1      2      3      4      5      6      7
 *   volts: 1.147  1.162  1.169  1.178  1.192  1.213  1.238  1.299
 *   level: 8      9      10     11     12     13     14     15
 *   volts: 1.336  1.457  1.573  1.707  1.882  2.06   2.32   2.58
 * </pre>
 *
 * <p>Jace's table is an AC amplitude with {@code VolTable[0] == 0}, whereas MAME's
 * raw output retains the ~1.147 V DC floor visible at level 0. So the quantity
 * asserted here is the <em>swing above level 0</em>, which is what is audible:
 * {@code (v[i] - v[0]) / (v[15] - v[0])}.
 *
 * <p><b>Measurements, not MAME's resistances.</b> MAME converts its resistance
 * table through {@code build_single_table}, a divider against {@code r_up = 800000},
 * {@code r_down = 8000000} and a load resistance; those resistances were fitted in
 * SwitcherCAD against the <em>ZX Spectrum's</em> output circuit. Jace has no such
 * network. Sweeping the load shows the model cannot reproduce the raw readings
 * exactly at any RL -- residual bottoms out at 0.0056 of full scale near RL = 1800,
 * and MAME's annotated RL = 2000 leaves 0.011, which is a 4.0 dB error at level 1
 * (35.6 dB level-1-to-15 span instead of the measured 39.6 dB). Correlation between
 * the two is 0.9990, so this is a small disagreement, but where they differ the
 * measurement is the ground truth and the divider is a model of foreign hardware.
 * These assertions therefore target the voltages directly and would still hold if
 * the table were ever regenerated by some other means.
 */
public class VolumeTableTest {

    /**
     * Westcott's measured voltages, normalized to the swing above level 0.
     * This is the empirical ground truth; everything else is a model of it.
     */
    private static final double[] WESTCOTT_NORMALIZED;
    static {
        double[] volts = {1.147, 1.162, 1.169, 1.178, 1.192, 1.213, 1.238, 1.299,
                          1.336, 1.457, 1.573, 1.707, 1.882, 2.06,  2.32,  2.58};
        WESTCOTT_NORMALIZED = new double[16];
        double span = volts[15] - volts[0];
        for (int i = 0; i < 16; i++) {
            WESTCOTT_NORMALIZED[i] = (volts[i] - volts[0]) / span;
        }
    }

    @Before
    public void setUp() {
        // VolTable is a lazily-built static; building it here rather than in a
        // @BeforeClass keeps this class from passing by accident when some other
        // test in the same JVM happened to build it first.
        Utility.setHeadlessMode(true);
        CardMockingboard.VolTable = null;
        new CardMockingboard().buildMixerTable();
    }

    /** The table normalized so that level 15 == 1.0. */
    private static double[] normalizedTable() {
        int[] t = CardMockingboard.VolTable;
        double[] n = new double[t.length];
        for (int i = 0; i < t.length; i++) {
            n[i] = (double) t[i] / (double) t[15];
        }
        return n;
    }

    @Test
    public void tableHasSixteenLevelsBecauseTheMockingboardUsesAnAyNotAYm2149() {
        assertEquals("the AY-3-8913 shares the AY-3-8910's 16-level DAC",
                     16, CardMockingboard.VolTable.length);
    }

    @Test
    public void silenceIsSilentAndLevelFifteenIsFullScale() {
        assertEquals("level 0 must be true silence", 0, CardMockingboard.VolTable[0]);
        assertTrue("level 15 must be the loudest level",
                   CardMockingboard.VolTable[15] > 0);
    }

    @Test
    public void tableIsMonotonicallyIncreasing() {
        int[] t = CardMockingboard.VolTable;
        for (int i = 1; i < 16; i++) {
            assertTrue("level " + i + " must be louder than level " + (i - 1)
                       + " (" + t[i] + " vs " + t[i - 1] + ")",
                       t[i] > t[i - 1]);
        }
    }

    @Test
    public void tableMatchesWestcottsMeasuredAyAmplitudes() {
        // The headline assertion. The tolerance is 0.001 of full scale -- integer
        // quantization at the default volume costs at most 9e-5 -- so this pins the
        // table to the measurement itself and not merely to something curve-shaped.
        // A uniform 3dB/step curve misses by 0.09 of full scale at level 9; MAME's
        // RL=2000 resistor reconstruction misses by 0.006 at level 1. Both fail here.
        double[] actual = normalizedTable();
        for (int i = 0; i < 16; i++) {
            assertEquals("level " + i + " must match the measured AY-3-8910 amplitude",
                         WESTCOTT_NORMALIZED[i], actual[i], 0.001);
        }
    }

    @Test
    public void stepsAreNonUniformAsMeasuredNotAConstantThreeDecibels() {
        // The whole point of using measured data: the real chip's steps are not
        // evenly spaced, and their size is not even monotonic in the level. The
        // measured swing steps by as little as 1.74 dB (14->15) and as much as
        // 4.46 dB (6->7). A synthesized logarithmic curve gives a dead-constant
        // 3.01 dB and is what this replaces.
        double[] n = normalizedTable();
        double smallest = Double.MAX_VALUE;
        double largest = 0.0;
        for (int i = 1; i < 15; i++) {
            double stepDb = 20.0 * Math.log10(n[i + 1] / n[i]);
            smallest = Math.min(smallest, stepDb);
            largest = Math.max(largest, stepDb);
        }
        assertTrue("the smallest step must fall below the uniform 3.01 dB "
                   + "(measured ~1.74 dB), was " + smallest, smallest < 2.25);
        assertTrue("the largest step must rise above it (measured ~4.46 dB), was "
                   + largest, largest > 4.0);
        assertTrue("the step size must genuinely vary across the range "
                   + "(measured ratio ~2.56), ratio was " + (largest / smallest),
                   largest / smallest > 2.0);
    }

    @Test
    public void everyIntermediateLevelSitsAboveAUniformLogCurve() {
        // The audible character of switching to measured data, asserted rather
        // than described in prose. The real chip's curve lies ABOVE a 3dB/step
        // model at every level between silence and full scale -- by +1.3 dB at
        // level 14, rising to a peak of +4.8 dB around levels 7-10. Nothing gets
        // quieter; the mid and low range get louder relative to full scale.
        double[] n = normalizedTable();
        for (int i = 1; i < 15; i++) {
            double uniform = 1.0 / Math.pow(Math.sqrt(2.0), 15 - i);
            assertTrue("level " + i + " must sit above the uniform 3dB/step curve ("
                       + n[i] + " vs " + uniform + ")", n[i] > uniform);
        }
        assertEquals("level 15 is the shared full-scale anchor", 1.0, n[15], 1e-9);
    }

    @Test
    public void usableDynamicRangeIsCompressedRelativeToAUniformCurve() {
        // Consequence of the above: because the quiet levels rise while full scale
        // stays put, the span from level 1 to level 15 shrinks from the uniform
        // model's 42.1 dB to the measured 39.6 dB. Quiet passages and envelope
        // decay tails are audibly less recessed than before.
        double[] n = normalizedTable();
        double measuredRangeDb = 20.0 * Math.log10(n[15] / n[1]);
        double uniformRangeDb = 20.0 * Math.log10(1.0 / (1.0 / Math.pow(Math.sqrt(2.0), 14)));
        assertTrue("measured range (" + measuredRangeDb + " dB) must be narrower than "
                   + "the uniform model's (" + uniformRangeDb + " dB)",
                   measuredRangeDb < uniformRangeDb);
        assertEquals("and should land near the measured 39.6 dB",
                     39.6, measuredRangeDb, 1.5);
    }

    @Test
    public void tableScalesWithTheConfiguredVolume() {
        // Installing a fixed measured curve must not break the volume control.
        CardMockingboard card = new CardMockingboard();
        card.volume = 100;
        card.buildMixerTable();
        int loud = CardMockingboard.VolTable[15];

        card.volume = 50;
        card.buildMixerTable();
        int quiet = CardMockingboard.VolTable[15];

        assertTrue("halving the volume must reduce full-scale output ("
                   + quiet + " vs " + loud + ")", quiet < loud);
        assertEquals("and should scale roughly linearly",
                     loud / 2.0, quiet, loud * 0.05);
    }

    @Test
    public void tableShapeIsIndependentOfVolumeSetting() {
        // The measured curve's shape is a property of the chip, not of the mixer,
        // so changing volume must not distort the relative levels.
        CardMockingboard card = new CardMockingboard();
        card.volume = 100;
        card.buildMixerTable();
        double[] loudShape = normalizedTable();

        card.volume = 40;
        card.buildMixerTable();
        double[] quietShape = normalizedTable();

        for (int i = 0; i < 16; i++) {
            assertEquals("level " + i + " relative shape must be volume-independent",
                         loudShape[i], quietShape[i], 0.01);
        }
    }
}
